name: Application CI
on: [ push, pull_request ]
jobs:
  applications:
    name: OncoKB Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17"
          cache: 'yarn'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Package application
        run: ./mvnw -ntp package -Pprod
