name: Release Management

on:
  workflow_run:
    workflows:
      - "After branch commit"
    branches:
      - rc
    types:
      - completed

jobs:
  update_draft_release:
    if: github.repository == 'oncokb/oncokb-curation'
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
